- runtime/src/main/java/com/fizzed/rocker/runtime/DefaultRockerBootstrap.java
The reformatting is due to IntelliJ's auto formatting which I do reflexively. Let me know if that's a problem and I'll trim things down.
> Load the model's template class via the same classloader that loaded the model class

- compiler/src/main/java/com/fizzed/rocker/compiler/TemplateParser.java
- argument statement string is trimmed down, possibly resulting in an
empty string which should be ok for proper no-argument handling.
> Potential (i.e. untested) fix for issue #17.

- compiler/src/main/java/com/fizzed/rocker/compiler/TemplateParser.java
- java6test/src/test/java/com/fizzed/rocker/RockerTest.java
- java6test/src/test/java/rocker/ArgsEmptyNoSpaces.rocker.html
- java6test/src/test/java/rocker/ArgsEmptyWithSpaces.rocker.html
- java6test/src/test/java/rocker/ArgsEmptyWithSpacesMultiline.rocker.html
The previous fix #18 didn't support empty argument lists spanning over multiple lines.
Added test cases for empty arguments.
> Empty args multiline

- compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- compiler/src/main/java/com/fizzed/rocker/compiler/RockerOptions.java
- compiler/src/main/java/com/fizzed/rocker/model/PostProcessorException.java
- compiler/src/main/java/com/fizzed/rocker/model/TemplateModelPostProcessor.java
- compiler/src/main/java/com/fizzed/rocker/processor/LoggingProcessor.java
- compiler/src/main/java/com/fizzed/rocker/processor/WhitespaceRemovalProcessor.java
- compiler/src/test/java/com/fizzed/rocker/compiler/TemplateParserTest.java
- compiler/src/test/resources/rocker/parser/OptionPostProcessing1.rocker.html
- compiler/src/test/resources/rocker/parser/OptionPostProcessing2.rocker.html
- compiler/src/test/resources/rocker/parser/OptionPostProcessing3.rocker.html
- docs/SYNTAX.md
- java6test/pom.xml
- java6test/src/test/java/com/fizzed/rocker/compiler/CompiledTemplateTest.java
- java6test/src/test/java/rocker/PostProcessing1.rocker.html
- maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java
- This option takes a comma-separated list of class names implementing
the TemplateModelPostProcessor interface.
- Before Java code is generated from templates in JavaGenerator, all
registered post-processors are called on the model, allowing them to
perform transformations on the model before Java code is created.
- Sample processors currently available are WhitespaceRemovalProcessor
and LoggingProcessor.
@jjlauer if this is more or less what you were having in mind, I hope this one is good to go. Let me know if you're not happy with the new package name ("processor"), or anything else (well, I know you will :-)
> Added option "postProcessing".

- compiler/src/main/java/com/fizzed/rocker/compiler/RockerOptions.java
thus made available it in runtime, otherwise it ignored while hot reloading working
> save postProcessing option to rocker-compiler.conf

- runtime/src/main/java/com/fizzed/rocker/runtime/PlainTextUnloadedClassLoader.java
I hit this when running tests with JaCoCo. It adds synthetic fields to all classes.
> Ignore synthetic fields when reading template fragments.

- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- rocker-test-java6/src/test/java/rocker/ForBlockWithWithBlock.rocker.html
- rocker-test-java8/src/test/java/rocker/ForBlockWithWithBlock.rocker.html
Pull request as promised. Seems Intellij changed some imports by itself when saving the file, hope you don't mind. I only noticed it now. ;)
"mvn clean install" succeeds for me.
Loop failed to compile. This happened with nested @with blocks that used
the variables in the text block. Fixed by making respective variables final where needed.
One test is currently disabled, the normal for loop as that requires more work to fix.
E.g. sample below @value.toString() below would not compile:
```
@for (BigDecimal value : list) {
@with (BigDecimal newObject =	value.stripTrailingZeros()) {
Inside with block, the line below didn't compile.
@value.toString()
}
}
```
> Fix issue where usage of variables from the @for

- docs/SYNTAX.md
- rocker-compiler/src/main/antlr4/com/fizzed/rocker/antlr4/WithBlockLexer.g4
- rocker-compiler/src/main/antlr4/com/fizzed/rocker/antlr4/WithBlockParser.g4
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/TemplateParser.java
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/WithBlockParserListener.java
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/WithStatementConsumerGenerator.java
- rocker-compiler/src/main/java/com/fizzed/rocker/model/WithStatement.java
- rocker-compiler/src/test/java/com/fizzed/rocker/bin/ParserMain.java
- rocker-compiler/src/test/java/com/fizzed/rocker/compiler/TemplateParserTest.java
- rocker-compiler/src/test/java/com/fizzed/rocker/model/WithStatementTest.java
- rocker-compiler/src/test/resources/rocker/parser/WithBlockMultipleArguments.rocker.html
- rocker-compiler/src/test/resources/rocker/parser/WithBlockMultipleArgumentsNullSafeFails.rocker.html
- rocker-runtime/src/main/java/com/fizzed/rocker/runtime/WithBlock.java
- rocker-test-java6/src/test/java/rocker/WithBlockWithMultipleArguments.rocker.html
- rocker-test-java8/src/test/java/rocker/WithBlockWithMultipleArgumentsJava8.rocker.html
Hey @jjlauer,
This is the pull request to make the with block support multiple arguments. It supports a single argument still of course, and multiple arguments now  as well (separated by a comma). By using a separate antlr parser to split the arguments correctly (you may be able to reuse that in the future, to parse other multi argument strings). So no escaping is necessary.
In addition the else is not allowed anymore for with? blocks with multiple arguments.
I've added tests for both java6 and java8. All new and existing tests (still) pass.
I also updated the syntax.md file  (I put a since version 0.15 for this, assuming you would bump the release to that version later, if not you need to change that). 
Could you merge this in and create a release later on?
Thanks!
Martijn
> @with block support for multiple arguments

- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- rocker-test-java6/src/test/java/com/fizzed/rocker/compiler/CompiledTemplateTest.java
This PR fixes issue #55 by omitting the `MODIFIED_AT` header field when the `optimize` compiler option is used.
> Pull request to address issue #55

- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGeneratorMain.java
This PR fixes a typo in the generator logging that states that rocker config file generation was skipped due to optimization being _off_. This is in fact incorrect as this happens when the optimize is _on_. 
This actually sent me off on a 30 minute expedition to figure out what I was doing wrong when passing option flags to the generator :)
> Fix typo in log message.

- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGeneratorMain.java
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGeneratorRunnable.java
- rocker-maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java
To make it easy to run the Rocker template generator programmatically, I've extracted most of the logic of JavaGeneratorMain into a separate class that implements Runnable. 
The main motivation here for me, is to allow using this generator together with the new Worker API in Gradle that expects a Runnable. Also splitting up the console logic in JavaGenerator from the actual runner is an improvement IMO.
> Extract runner logic from JavaGeneratorMain into Runnable interface

- rocker-runtime/src/main/java/com/fizzed/rocker/runtime/DefaultRockerTemplate.java
- rocker-runtime/src/test/java/com/fizzed/rocker/runtime/DefaultRockerTemplateTest.java
This is a fix for https://github.com/fizzed/rocker/issues/68 with according unit test.
> Fix for Issue-68; Check nullsafe for RockerContent

- docs/SYNTAX.md
@Rocker("views/MyOther.rocker.html", "myArg1", "Another arg")
should be
@Rocker.template("views/MyOther.rocker.html", "myArg1", "Another arg")
(I think?)
> call another template dynamically syntax

- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/TemplateCompiler.java
- rocker-compiler/src/main/java/com/fizzed/rocker/model/JavaVersion.java
- rocker-maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java
Remove @Generated annotation as it's broken in java 9+
Fall back to java.class.path property when Thread#getContextClassLoader doesn't return an URLClassLoader
Handle major version 9
Fixes #73
> Add support for Java 9

- pom.xml
- rocker-compiler/src/main/java/com/fizzed/rocker/model/JavaVersion.java
Currently using Java 10 and above results in the following error:
```
[ERROR] Failed to execute goal com.fizzed:rocker-maven-plugin:0.24.0:generate (generate-rocker-templates) on project market: Unsupported javaVersion [10] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
Rocker seems to run w/o a problem on higher Java versions, as long as you lie in the `rocker.javaVersion` inside your pom, so I've just added two new entries to the JavaVersion enum.
~~Beside …
> Add JDK10 support

- README.md
Fixed to reflect the actual system property name checked in com.fizzed.rocker.runtime.RockerRuntime
> Fix hot reload system property name in readme

- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- rocker-compiler/src/main/java/com/fizzed/rocker/reload/ReloadingRockerBootstrap.java
- rocker-compiler/src/test/resources/generated/Args.java.txt
- rocker-runtime/src/main/java/com/fizzed/rocker/Rocker.java
- rocker-test-java6/src/test/java/com/fizzed/rocker/compiler/CompiledTemplateTest.java
- Replace public static constant fields with static methods in the template classes
This is a fix for https://github.com/fizzed/rocker/issues/88
I've tested the incremental compilation manually and now it works as expected without forcing gradle to recompile everything everytime a template class has changed.
I'm looking forward to your feedback. all tests passed locally for me.
> Fix incremental java compilation with rocker and Gradle

- .travis.yml
- pom.xml
- rocker-compiler/src/main/java/com/fizzed/rocker/model/JavaVersion.java
https://travis-ci.org/drauf/rocker/builds/437732529
closes #90 
This adds a _MODERN_ value to the JavaVersion enum, that all Java versions after 9 will be assigned to.
In the code the value of this enum is only used in five places:
- twice to assert if the JVM running is at least Java 8 (the _int version_)
- once in an error message (the _String label_)
- twice to serialize and deserialize config (the _String label_)
The config serialization won't break after removing the two options from the enum, because they will still be parsed as the _MODERN_ value.
> Handle autodetection of Java 11

- README.md
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/JavaGenerator.java
- rocker-compiler/src/main/java/com/fizzed/rocker/compiler/RockerOptions.java
- rocker-gradle-plugin/src/main/java/com/fizzed/rocker/gradle/RockerConfiguration.java
- rocker-gradle-plugin/src/main/java/com/fizzed/rocker/gradle/RockerTask.java
- rocker-maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java
- rocker-runtime/src/main/java/com/fizzed/rocker/Generated.java
@jjlauer this is my initial attempt at #116.
I haven't made the feature configurable yet, because there is something I want to discuss first.
My intention was to apply the annotation to every class rocker generates. The catch is, that rocker generates:
* anonymous classes for java 6 and 7
* lambas for java 8
Right now java does not allow annotations on either of them.
For anonymous classes there might be a solution in the form of JSR308 (Introduced in java 8).
```java
callMethod(new @Generated AnonymousClass(){})
```
But this also has it's problems:
1. I don't think JaCoCo supports JSR308 annotations.
2. This only works for anonymous classes. Those are only generated by rocker on the <8 java profile. But JSR308 requires at least java 8.
Those are the options we have in the order my …
> Mark generated classes as generated #116

- .travis.yml
- rocker-compiler/src/main/java/com/fizzed/rocker/model/JavaVersion.java
- rocker-compiler/src/test/java/com/fizzed/rocker/model/JavaVersionTest.java
- rocker-gradle-plugin/src/main/java/com/fizzed/rocker/gradle/RockerTask.java
- rocker-maven-plugin/src/main/java/com/fizzed/rocker/maven/GenerateMojo.java
Provides the correct Java version from System property `java.version`.
Applies same functionality for both Maven and Gradle plugins.
Fixes #120
> Obtain current Java version from system property

- README.md
- rocker-runtime/src/main/java/com/fizzed/rocker/BindableRockerModel.java
- rocker-test-java6/src/test/java/com/fizzed/rocker/bin/RockerTest.java
This allows a relaxed bind (as discussed on #122).
Includes a simple test and small readme update.
> #122: Initial proposal for relaxed bind

- rocker-gradle-plugin/src/main/java/com/fizzed/rocker/gradle/RockerConfiguration.java
This implements the changes suggested in #143. The behaviour is not changed but the Gradle plugin is now compatible with Gradle 7.
> Add compatibility for Gradle 7 (Fix #143)
